name: bingo
description: A bingo app for lectures and classes.

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  archive: any
  auto_size_text: any
  auto_size_text_field: any
  barcode_scan: ^1.0.0
  carousel_slider: any
  cloud_firestore: ^0.9.13
  cupertino_icons: ^0.1.2
  data_classes: ^3.0.0
  firebase_analytics: ^2.1.1+2
  hero_material:
    path: ../hero_material
  qr_flutter: ^2.0.0
  rxdart: ^0.21.0
  shared_preferences: ^0.5.2
  screen: ^0.0.5
  time: any
  black_hole_flutter: any
  flutter_deep_linking: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  data_classes_generator: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Signature
      fonts:
        - asset: "assets/NotoSans-Bold.ttf"
    - family: Futura
      fonts:
        - asset: "assets/Futura Book.ttf"
          weight: 400
        - asset: "assets/Futura Bold.ttf"
          weight: 700
