name: bingo
description: A bingo app for lectures and classes.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: ^1.1.2
  barcode_scan: ^1.0.0
  cloud_firestore: ^0.9.13
  cupertino_icons: ^0.1.2
  qr_flutter: ^2.0.0
  rxdart: ^0.21.0
  screen: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Signature
      fonts:
        - asset: "assets/NotoSans-Bold.ttf"
